### ISSUE TITLE
Removing the .dll suffix from the NuGet package

### ISSUE THREAD

**Issue by jamesqo** [DotNetCross/Memory.Unsafe#1]
Hi! I came across your library from the link you posted in [dotnet/coreclr](https://github.com/dotnet/coreclr/issues/2322#issuecomment-195768873). I know this is a bit of an odd/silly issue to raise, but would you be willing to accept a PR that removes the `.dll` suffix from the package name? The reason being is that I'm considering using this package from another library of mine, and it just looks a bit odd to have a `.dll` in the package name (which will be seen by users of my package when it's installed alongside mine from NuGet).

Thanks!

**Comment by nietras** [comment]
Hi, that is a mistake on my part. I guess this will be a breaking change in the package, since changing the package name will mean it will no longer refer to the old package name, right?

There is also an issue with package having the same dll many times to support all platformns. I thought putting it in just `lib` would make it compatible with all platforms but it does not work.

**Comment by nietras** [comment]
Hmm just trying changing it and uploading to NuGet and got the following error:
```
The ID of your package, 'DotNetCross.Memory.Unsafe', is similar to the title of an existing package, which can cause confusion with our users. Please modify the ID of your package and try uploading again.
```
which means I would probably have to delete the old package first, which would break anyone using the package already, which is probably few, but it would be great if there was another way to fix this...

**Comment by nietras** [comment]
The old package has now been deleted and new uploaded without the `.dll` name, also see https://github.com/NuGet/NuGetGallery/issues/2941.

**Comment by jamesqo** [comment]
Was busy this morning, so unfortunately I didn't have time to reply to your earlier comments. Thanks for taking the time to fix this :smile:
