### ISSUE TITLE
Consider typed pointers

### ISSUE THREAD

**Issue by dzmitry-lahoda** [DotNetCross/Memory.Unsafe#10]
Update [2018-05-09]: C# 7.3 introduced the unmanaged constraint. You can now write generic pointer deref code directly in C#, e.g.
```
    static unsafe T Read<T>(T* ptr) where T: unmanaged {
        return *ptr;
    }
```

**Comment by nietras** [comment]
Right, which means there is no need for such a method you can just write `*ptr`, the `Read` in unsafe can be used for other types than `unmanaged` so it still need to be done in IL.
